START_CALIBRATION = 'SCRIPTLOADER_START_CALIBRATION'
STOP_CALIBRATION = 'SCRIPTLOADER_STOP_CALIBRATION'
START_RECORDING = 'SCRIPTLOADER_START_RECORDING'
STOP_RECORDING = 'SCRIPTLOADER_STOP_RECORDING'
TRIGGER = 'SCRIPTLOADER_TRIGGER'

EXIT = 'SCRIPTLOADER_EXIT'
ACTION_CALIBRATION = 'SCRIPTLOADER_ACTION_CALIBRATION'
ACTION_RECORDING = 'SCRIPTLOADER_RECORDING_CALIBRATION'