START_CALIBRATION = 'SCRIPTLOADER_START_CALIBRATION'
STOP_CALIBRATION = 'SCRIPTLOADER_STOP_CALIBRATION'
START_RECORDING = 'SCRIPTLOADER_START_RECORDING'
STOP_RECORDING = 'SCRIPTLOADER_STOP_RECORDING'
TRIGGER = 'SCRIPTLOADER_TRIGGER'

EXIT = 'SCRIPTLOADER_EXIT'
ACTION_CALIBRATION = 'SCRIPTLOADER_ACTION_CALIBRATION'
ACTION_RECORDING = 'SCRIPTLOADER_RECORDING_CALIBRATION'

# CBSC: callback status codes
#  > 0: Task not done
# == 0: Task finished gracefully
#  < 0: Task failed

CBSC_STATUS_UNSPECIFIED = -1
CBSC_PROCEDURE_ALREADY_INITIATED = 99

CBSC_CALIBRATION_SUCCESSFULL = 0
CBSC_CALIBRATION_FAILED = -2

CBSC_RECORDING_STARTED = 1
CBSC_RECORDING_STOPPED = 0